### ISSUE TITLE
No Licence Statement

### ISSUE THREAD

**Issue by jones139** [otonchev/rtspviewersf#2]
Hi,
Thank you for publishing the source code of this app - I would never have worked out how to compile gstreamer on android and use it to play audio/video streams that are not supported by Android.
I would like to use this as the basis of a video monitor app for my project (http://openseizuredetector.org.uk), but there is no licence statement in this repository or the source code - would you mind if I use it (with an appropriate acknowledgement for yourself of course!)?

Thanks

Graham.

**Comment by jones139** [comment]
But I did just find a GPL statement in some of the source files, so I think that probably answered my question?
Thanks again

Graham.

**Comment by otonchev** [comment]
Hi Graham,

nice to hear that my project has helped you, yes, the intent was GPL but i
have apparently missed the GPL statement in many of the files :)
But use the code the way you like :)

Regards
